name: Build and Test
on: [push]

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm format

  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.56.1-noble
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/

      # - name: Install playwright dependencies
      #   run: pnpm -F playwright exec playwright install --with-deps

      - name: Build library
        run: pnpm -F react-async-modal-hook build # Required for tests

      - name: Run tests
        run: pnpm test

      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright
          path: "**/.playwright/**"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm build
